/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */



#include "Platforms_Types.h"
#include "stm32f103c.h"
	volatile Registers * GPIOAODR=(volatile Registers *) GPIO_Port_A_ODR;
	volatile Registers * GPIOACRH=(volatile Registers *)GPIO_Port_A_CRH;
	volatile Registers * RCCAPB=(volatile Registers *)RCC_APB2ENR;
int main(void)
{
	RCCAPB->pins.pin2=1;
	 GPIOACRH->pins.pin19=0;
	 GPIOACRH->pins.pin20=1;
	 GPIOACRH->pins.pin21=0;
	 GPIOACRH->pins.pin22=0;



	while(1){
		int i=0;
		for(i=0;i<5000;i++);
		GPIOAODR->pins.pin13=1;
		for(i=0;i<5000;i++);
		GPIOAODR->pins.pin13=0;
		for(i=0;i<5000;i++);
	}


}
